### PR TITLE
convert to a Python package.

### PR DESCRIPTION
**Pull request by rainwoodman**
```
pip install runtests
python run-tests.py
```

### CODE REVIEW

**Comment by rainwoodman** [comment]
These are additional python features.
Makefile for the C library still works as previously.
setup.py will however build the so file via the python way, bypassing Makefile.

run-test.py is a pytest interface we use to always reinstall and allows --pdb at failure.

**Comment by manodeep** [comment]
@rainwoodman Does this work for both python2 and python3?

**Comment by rainwoodman** [comment]
Good catch. Fixed.

**Comment by pec27** [comment]
@rainwoodman 
This looks great, thanks for working on this! I'm not super-familiar with runtests.py (I should probably learn...), I note that when I do `python run-tests.py` I get 
> Exception: Library .....build/testenv/lib64/python2.7/site-packages/hfof/libhfof.so does not exist. Maybe you forgot to make it?

when I think with the setup you used it is now built as `hfof.libhfof.so` (I've no strong preferences on convention, but probably it should be consistent).

A couple of small things:
in setup.py can you make the line `extra_compile_args=['-O2', '-g', '-std=c99'],` as I use some c99 (need to say explicitly for some gcc) and I only get a slower compile time from -O3 vs. -O2 (actually I'm not sure why you need -g, but maybe you have some debugging integration?). Also the license is MIT not GPL3.

Thanks again for your help.

**Pull request merged**
